### PR TITLE
Remove unnecessary slash

### PR DESCRIPTION
**Pull request by LostCrew**
@netpi Let's bring this in, it's tragically useful

### CODE REVIEW

**Comment by netpi** [comment]
@LostCrew @moonlik 
https://github.com/vue-bulma/pagination/blob/master/src/Pagination.vue#L57 
this function has fix  `//` to `/` , but do you mean no `/` needed ?

**Comment by LostCrew** [comment]
Hi @netpi,
your link to the specific line seems off. The PR simply removes the `/` between `urlPrefix` and the previous/next page number. That way, it would support `urlPrefix` with query string (like `/?page=`).

**Comment by netpi** [comment]
@LostCrew @moonlik  
OK, please resolve conflicts and I will merge

**Comment by LostCrew** [comment]
@moonlik Could you take care of the conflicts?

**Comment by moonlik** [comment]
@netpi, @LostCrew done

**Comment by netpi** [comment]
@moonlik @LostCrew 

this problem has been fixed by https://github.com/vue-bulma/pagination/pull/16.  

see this example. thanks

```js
<template>
  <div class="container">
    <pagination :urlBuilder="urlBuilder" :currentPage="2" :lastPage="100" />
  </div>
</template>

<script>
import Pagination from 'vue-bulma-pagination/src/Pagination'

export default {
  components: {
    Pagination
  },

  methods: {
    urlBuilder (page) {
      return { query: { ...this.$route.query, page } } // Changing page in location query
    }
  }
}
</script>
```

**Pull request closed without merging**
